"""empty message

Revision ID: 182fb2b171af
Revises: 59e39cde4fc3
Create Date: 2024-12-24 20:11:29.480520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '182fb2b171af'
down_revision: Union[str, None] = '59e39cde4fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'updated_ts')
    op.drop_column('categories', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('updated_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
