"""empty message

Revision ID: 59e39cde4fc3
Revises: f61cef8de5a8
Create Date: 2024-12-24 20:05:28.270286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e39cde4fc3'
down_revision: Union[str, None] = 'f61cef8de5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'updated_by')
    # ### end Alembic commands ###
