"""empty message

Revision ID: 61bc63f1a8fc
Revises: 85b8f668b355
Create Date: 2024-12-24 19:57:54.955294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bc63f1a8fc'
down_revision: Union[str, None] = '85b8f668b355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categorized_data_2024-12-24_index', table_name='categorized_data_2024-12-24')
    op.drop_table('categorized_data_2024-12-24')
    op.drop_index('ix_raw_data_2024-12-24_index', table_name='raw_data_2024-12-24')
    op.drop_table('raw_data_2024-12-24')
    op.drop_index('ix_transformed_data_2024-12-24_index', table_name='transformed_data_2024-12-24')
    op.drop_table('transformed_data_2024-12-24')
    op.add_column('categories', sa.Column('updated_ts', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'updated_ts')
    op.create_table('transformed_data_2024-12-24',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Mode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Payee Account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Payee', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Account', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_transformed_data_2024-12-24_index', 'transformed_data_2024-12-24', ['index'], unique=False)
    op.create_table('raw_data_2024-12-24',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_raw_data_2024-12-24_index', 'raw_data_2024-12-24', ['index'], unique=False)
    op.create_table('categorized_data_2024-12-24',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Mode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Payee Account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Payee', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Category', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_categorized_data_2024-12-24_index', 'categorized_data_2024-12-24', ['index'], unique=False)
    # ### end Alembic commands ###
